[package]
name = "genpeerid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = "0.5.1"
ed25519-dalek = "2.1.1"
anyhow = "1.0.81"
