name: Build and Publish Binary

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build binary with PyInstaller
        run: |
          pyinstaller --onefile --clean src/genpeerid.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: genpeerid
          path: dist/genpeerid
